updated token sale setup proxy and token collection issuer contract
ergo-pad/ergopad-random-nft-sale-contracts pull request #2
Opened 2022-10-16 23:11 UTC by lucagdangelo

2022-10-19 08:27 UTC, Luivatra requested changes
I am a bit confused about your usage of context vars. what is stopping the tx operator from inserting garbage?

2022-10-19 08:27 UTC, Luivatra commented on src/main/scala/contracts/token_sale_setup_proxy/v1.0.0/ergoscript/Token_Sale_Setup_Proxy.es
> +                (tokenCollectionIssuerBoxOUT.propositionBytes == TokenCollectionIssuerProxyContractBytes)
probably just a copypaste error, think this should be TokenCollectionIssuerContractBytes

2022-10-19 08:27 UTC, Luivatra commented on src/main/scala/contracts/token_sale_setup_proxy/v1.0.0/ergoscript/Token_Sale_Setup_Proxy.es
> +                    (tokenCollectionIssuerBoxOUT.R8[Coll[(Coll[Byte], Coll[Byte])]].get == CollectionAdditionalInfo)
these values come from context vars, so they can be anything the tx operator wants

2022-10-19 08:27 UTC, Luivatra commented on src/main/scala/contracts/token_collection_issuer_proxy/v1.0.0/ergoscript/Token_Collection_Issuer.es
> +    val CollectionTokenPictureLink: Coll[Byte] = Coll[Byte]() // Should just be empty Coll[Byte](), if Utility-Token
The tx operator decides the context variables, so they can insert whatever they want

2022-10-21 22:59 UTC, lucagdangelo commented
I added the TxOperatorPK as a condition for singing and fixed the typos

2022-10-22 01:57 UTC, merged